### ISSUE TITLE
Producer -> Streams task 문제

### ISSUE THREAD

**Issue by JY-1019** [YBIGTA-DE/EC2-Dashboard#12]
1. 
Producer 에서 먼저 각 ec2에 카프카를 설치해서 올리는데 그럼 각 Topic에 정보가 저장되어 있는데 해당 구조는 카프카의 장점을 살리기 어려운 구조 
=>해당 구조로는 추후 분산처리 Task는 어려울 수 있습니다
2.
Streams에서 데이터를 받아와서 join할때 Producer 에서 어떻게 데이터를 저장할 것인지 알지 못하면 진행하기 어려움 => 코드 자체는 굉장히 간단함
3.
제안 사항 => 각 Producer에 websocket을 구현하고 kafka는 따로 서버 하나를 두는 것이 간단할 것으로 보임 => 오픈소스 처럼 서비스를 제공하는 것도 사실 이런식으로 진행하는 것이 가장 바람직해 보인다.

**Comment by jk121925** [comment]
1. producer에서 각 ec2에 카프카를 설치할 필요는 없는 것으로 이전회의 때 이야기 했습니다!

2. Streams에서 데이터를 받는 부분은 종연님의 의견을 반영하여 진행하는 것으로 이야기 되었습니다!
    a. 전체 하드웨어의 CPU, Memory, Disk 사용량을 지속적으로 평균을 내줍니다.
    b. 이후 전체 평균 보다 x1.5 ~ x2.0정도인 사용량을 경고 알람을 통해 시각화합니다.

3.  websocket을 따로 진행하지 않고 producer를 daemon으로 놓고 진행하는 방향으로 프로젝트를 진행하는게 좋을 것 같습니다.

다른의견이 있다면 Comment를 남겨 주시거나 회의를 진행할 때 알려주세요!

**Comment by jk121925** [comment]
1. producer에서 각 ec2에 카프카를 설치할 필요는 없는 것으로 이전회의 때 이야기 했습니다!

2. Streams에서 데이터를 받는 부분은 종연님의 의견을 반영하여 진행하는 것으로 이야기 되었습니다!
a. 전체 하드웨어의 CPU, Memory, Disk 사용량을 지속적으로 평균을 내줍니다.
b. 이후 전체 평균 보다 x1.5 ~ x2.0정도인 사용량을 경고 알람을 통해 시각화합니다.

3. websocket을 따로 진행하지 않고 producer를 daemon으로 놓고 진행하는 방향으로 프로젝트를 진행하는게 좋을 것 같습니다.

다른의견이 있다면 Comment를 남겨 주시거나 회의를 진행할 때 알려주세요!
