### ISSUE TITLE
public ip 매개변수로 입력 받기

### ISSUE THREAD

**Issue by woohoocheezy** [YBIGTA-DE/EC2-Dashboard#8]
producer 실행 시 자바 main 함수에 매개 변수로 kafka broker public ip 입력 받아서 producer 연결

**Comment by woohoocheezy** [comment]
### 구현 방법
java main function의 매개변수로 받아와서 입력 받아오도록 구현

### 사용법 예시
java -jar producer-0.0.1-SNAPSHOT.jar 1231.11.1.1

**Comment by jk121925** [comment]
확인했습니다~
